version: "3.7"

services:
  app:
    build: .
    container_name: django-dev
    restart: always
    env_file:
      - django.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000

